### ISSUE TITLE
Build commands

### ISSUE THREAD

**Issue by benjamin-richardson** [piratefsh/js-motion-detector#1]
Hi Sher, 

I was firing up your motion-detector and ran into an issue of missing the motion-detect.js file. To fix this I ran the command 'webpack --config webpack.config.prod.js' instead of the listed 'webpack --config webpack.config.js' command. 

The motion-detect.js was built and I would run the app with the serve command. 

Great talk.js presentation tonight. Very fun little app to mess around with. 

Cheers, Ben

**Comment by piratefsh** [comment]
Hey thanks! I was experimenting with packaging it as a library and accidentally committed some of it. I have since reverted and included the MotionDetect as an import in index.js. Good catch!
